{"uuid": "a8d1f5e8-1ce3-4a42-bb1d-90672eee0134", "children": ["6c664055-7ae2-4a0d-8de6-6cf4a64e03c7"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\nStacktrace:\n\tGetHandleVerifier [0x00E5E123+48179]\n\t(No symbol) [0x00DE5D01]\n\t(No symbol) [0x00CCD5F0]\n\t(No symbol) [0x00CC1743]\n\t(No symbol) [0x00CF8449]\n\t(No symbol) [0x00CF3EC7]\n\t(No symbol) [0x00CF0A69]\n\t(No symbol) [0x00D2CA51]\n\t(No symbol) [0x00D2C5FA]\n\t(No symbol) [0x00D23A26]\n\t(No symbol) [0x00CFB7BC]\n\t(No symbol) [0x00CFC62D]\n\tGetHandleVerifier [0x01177C33+3299139]\n\tGetHandleVerifier [0x011B5BF2+3553026]\n\tGetHandleVerifier [0x011B0BCC+3532508]\n\tGetHandleVerifier [0x00EF494E+664670]\n\t(No symbol) [0x00DF0AB4]\n\t(No symbol) [0x00DEBF08]\n\t(No symbol) [0x00DEC02D]\n\t(No symbol) [0x00DDDD00]\n\tBaseThreadInitThunk [0x756B6839+25]\n\tRtlGetFullPathName_UEx [0x7769906F+1215]\n\tRtlGetFullPathName_UEx [0x7769903D+1165]\n\n", "trace": "  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\testcases\\conftest.py\", line 25, in setup\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 209, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 293, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708519139837, "stop": 1708519271398}], "start": 1708519139837, "stop": 1708519272482}