{"uuid": "c7824bbb-d296-4d83-bf77-5afb245ee3ae", "children": ["e2b8e08c-4af6-4d35-877a-b8f004e3e05f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\nStacktrace:\n\tGetHandleVerifier [0x00B9E123+48179]\n\t(No symbol) [0x00B25D01]\n\t(No symbol) [0x00A0D5F0]\n\t(No symbol) [0x00A01743]\n\t(No symbol) [0x00A38449]\n\t(No symbol) [0x00A33EC7]\n\t(No symbol) [0x00A30A69]\n\t(No symbol) [0x00A6CA51]\n\t(No symbol) [0x00A6C5FA]\n\t(No symbol) [0x00A63A26]\n\t(No symbol) [0x00A3B7BC]\n\t(No symbol) [0x00A3C62D]\n\tGetHandleVerifier [0x00EB7C33+3299139]\n\tGetHandleVerifier [0x00EF5BF2+3553026]\n\tGetHandleVerifier [0x00EF0BCC+3532508]\n\tGetHandleVerifier [0x00C3494E+664670]\n\t(No symbol) [0x00B30AB4]\n\t(No symbol) [0x00B2BF08]\n\t(No symbol) [0x00B2C02D]\n\t(No symbol) [0x00B1DD00]\n\tBaseThreadInitThunk [0x756B6839+25]\n\tRtlGetFullPathName_UEx [0x7769906F+1215]\n\tRtlGetFullPathName_UEx [0x7769903D+1165]\n\n", "trace": "  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\testcases\\conftest.py\", line 25, in setup\n    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 61, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 209, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 293, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 348, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Cred_Rev2\\TestFrameworkDemo\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1708519139837, "stop": 1708519290319}], "start": 1708519139837, "stop": 1708519290790}